spring:
  application:
    name: hzzh-acs
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  main:
    log-startup-info: false
    lazy-initialization: false
    banner-mode: log
logging:
  include-application-name: true
  file:
    name: my.log
  register-shutdown-hook: false
debug: false
trace: false