spring:
  config:
    import: classpath:application-redis.yaml,classpath:application-dal.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: DEBUG

